### ISSUE TITLE
bs4 "AttributeError: 'NoneType' & Object has no attribute 'find_all'

### ISSUE THREAD

**Issue by Ebiscusnus** [yeuci/anime-scraper#1]
I don't know if this is still maintained but I used this a couple years back to download videos, I get the "AttributeError: 'NoneType' error and a "has no attribute 'find_all' when trying to run the script on any slug. I've tried this on many different Gogo variants.

![Screenshot 2023-06-19 014920](https://github.com/yeuci/anime-scraper/assets/40144685/f52475aa-0251-4649-ab6d-de34fe649ae4)

**Comment by yeuci** [comment]
> I don't know if this is still maintained but I used this a couple years back to download videos, I get the "AttributeError: 'NoneType' error and a "has no attribute 'find_all' when trying to run the script on any slug. I've tried this on many different Gogo variants.
> 
> ![Screenshot 2023-06-19 014920](https://user-images.githubusercontent.com/40144685/246736737-f52475aa-0251-4649-ab6d-de34fe649ae4.png)

It works on https://ww5.gogoanimes.org/
They closed the .sh version so most of the wp cms clones arent using the same structure
